# Generated by Django 2.2.1 on 2019-05-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='PhoneNumber',
            field=models.CharField(default=626, max_length=10),
            preserve_default=False,
        ),
    ]
