# Generated by Django 2.2.1 on 2019-05-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_donations_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='PaymentStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donations',
            name='RequestId',
            field=models.CharField(default=465, max_length=100),
            preserve_default=False,
        ),
    ]
