# Generated by Django 2.2.1 on 2019-06-02 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_auto_20190530_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='DonationAmount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(20)]),
        ),
    ]
