# Generated by Django 2.2.1 on 2019-06-02 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_auto_20190602_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donations',
            name='PhoneNumber',
        ),
    ]
